services:
  app-service:
    # DONE: change "letsgetrusty" to your Docker Hub username
    image: jeffprestes/app-service # specify name of image on Docker Hub
    restart: "always" # automatically restart container when server crashes
    environment: # set up environment variables
      AUTH_SERVICE_IP: ${AUTH_SERVICE_IP:-localhost} # Use localhost as the default value
    ports:
      - "8000:8000" # expose port 8000 so that applications outside the container can connect to it 
    depends_on: # only run app-service after auth-service has started
      auth-service:
        condition: service_started
  auth-service:
    # DONE: change "letsgetrusty" to your Docker Hub username
    image: jeffprestes/auth-service
    environment:
      JWT_SECRET: "minha_chave_secreta_super_secreta"
      DATABASE_URL: "postgres://rust:teste@host.docker.internal:5432/postgres"
      POSTGRES_PASSWORD: "teste"
      REDIS_URL: "redis://host.docker.internal:6379"
    restart: "always" # automatically restart container when server crashes
    ports:
      - "3000:3000" # expose port 3000 so that applications outside the container can connect to it 